name: dart_course_test
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/Colman1000/dart-course-test

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
